version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - .:/app
    links:
      - db
    restart: always

  pinger:
    build:
      context: .
    command:  /bin/bash -c "bundle exec ruby apps/daemons/pinger.rb"
    volumes:
      - .:/app
    links:
      - db
    restart: always

  db:
    image: timescale/timescaledb:latest-pg12
    volumes:
      - database:/var/lib/postgresql/data/pg_data
    environment:
      POSTGRES_USER: ruby
      POSTGRES_PASSWORD: ruby
      PGDATA: /var/lib/postgresql/data/pgdata

volumes:
  database:
