version: "3.9"  # optional since v1.27.0

services:
  app:
    build:
      context: .
    command: /bin/bash -c "while true; do sleep 1; done"
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - .:/app
    links:
      - pg
    environment:
      - INSTANCE
      - DB_HOST=pg
    restart: always

  pg:
    image: postgres
    volumes:
      - ./local/postgres/pgdata:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: ruby
      POSTGRES_PASSWORD: ruby
      PGDATA: /var/lib/postgresql/data/pgdata

  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports: ['127.0.0.1:5071:8080']
    restart: always
